apiVersion: v1
kind: Secret
metadata:
  name: api-key-secret
  namespace: backend-namespace
type: Opaque
data:
  API_KEY: QWl6YVN5RDFFU2o1NURkSnNJS2RkdGpLcW5NUUNTbmJjQ1JudlpFeTZ-awo= # echo -n "AIzaSyD1ESj55DdJsIKddtjKqnMQCRnVzEy6-ik" | base64
