apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/micro-docker-test/gemini-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: API_KEY
          value: "AIzaSyD1ESj55DdJsIKddtjKqnMQCRnVzEy6-ik"
