apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend-namespace
spec:
  type: LoadBalancer
  loadBalancerIP: 34.67.42.139
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000