apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/micro-docker-test/gemini-frontend:latest
        ports:
        - containerPort: 3000